### ISSUE TITLE
프론트엔드 Todo - 김유림

### ISSUE THREAD

**Issue by tjwdud** [tjwdud/git-farm#23]
In GitLab by @Kimyurim on Feb 10, 2022, 17:09

- [x] 목표 설정 페이지
  - [x] 목표 설정 페이지 추가 마크업
  - [x] 목표 다짐 이미지 랜덤으로 보이는 기능 추가
- [x] Goal-Input-Modal
  - [x] Type(일별 목표 커밋, Resolution)에 따라 내용이 달라지게끔 변경
  - [x] Type에 따른 input type 변경(number, text)
  - [x] 목표 설정 입력 -> input 값 저장 함수 추가
  - [x] 목표 설정(resolution) POST, GET API 구성 요청

**Comment by tjwdud** [comment]
In GitLab by @Kimyurim on Feb 10, 2022, 18:50

marked the task **목표 설정 입력 -> input 값 저장 함수 추가** as completed

**Comment by tjwdud** [comment]
In GitLab by @Kimyurim on Feb 10, 2022, 18:51

marked the task **목표 설정 페이지** as completed

**Comment by tjwdud** [comment]
In GitLab by @Kimyurim on Feb 10, 2022, 20:30

marked the task **목표 설정(resolution) POST, GET API 구성 요청** as completed

**Comment by tjwdud** [comment]
In GitLab by @Kimyurim on Feb 10, 2022, 20:30

marked the task **Goal-Input-Modal** as completed
